version: "3.7"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes: 
      - ./mosquitto.conf:/mostquitto/config/mosquitto.conf